![.github/workflows/docker.yml](https://github.com/k6io/example-github-actions/workflows/.github/workflows/docker.yml/badge.svg?branch=master&event=push)

jobs:
  k6_local_test:
    name: k6 local test run - docker example
    runs-on: ubuntu-latest
    container: docker://loadimpact/k6:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Local k6 test
        run: k6 run docker/script.js
