name: Local Service Workflow
on: [push]

jobs:
  runner-job:
    runs-on: ubuntu-latest

    services:
      quickpizza:
        image: ghcr.io/grafana/quickpizza-local:latest
        ports:
          - 3333:3333
          
    steps:
      - name: Checkout
        uses: actions/checkout@v4
  
      - name: Run local k6 test
        uses: grafana/k6-action@v0.3.1
        with:
          filename: local-service/script.js
        env:
          BASE_URL: "http://localhost:3333"